import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavFooter from "./footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "McDonalds",
  description: "Generated by create next app",
};

let transform = "iPhoneTransform ";

// function iOS() {
//   return [
//     'iPad Simulator',
//     'iPhone Simulator',
//     'iPod Simulator',
//     'iPad',
//     'iPhone',
//     'iPod'
//   ].includes(navigator.platform)
//   // iPad on iOS 13 detection
//   || (navigator.userAgent.includes("Mac") && "ontouchend" in document)
// }

// if (iOS()) {
//   transform = "iPhoneTransform "
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/favicon.ico" sizes="any"/>
        <link
          rel="icon"
          href="/images/icon?<generated>"
          type="image/<generated>"
          sizes="<generated>"
        />
        <link rel="manifest" href="/manifest/manifest.webmanifest"/>
        <meta name='viewport' content='initial-scale=1, viewport-fit=cover, width=device-width'/>
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
      </head>
      <body className={transform + " flex flex-col " + inter.className}>
        {children}
        <NavFooter />
      </body>
    </html>
  );
}
